spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/fullDesign
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
storage:
  upload_dir: uploads